Repository alloy-rs/trie, pull requests merged in 2024-10, with the labels that each got.

#56 fix: use vector of arbitrary length for leaf node value
  src/hash_builder/mod.rs
  src/nodes/branch.rs
  src/nodes/leaf.rs
  src/nodes/mod.rs
  src/proof/verify.rs
Labels: bug

#57 feat: `RlpNode::as_hash`
  src/nodes/rlp.rs
Labels: enhancement

#58 feat(mask): unset bit, count set bits, index of the first set bit
  src/mask.rs
Labels: enhancement

#61 docs(nodes): adjust comments about branch node masks
  src/hash_builder/mod.rs
  src/nodes/branch.rs
Labels: documentation
